## Random

In [1]:
import numpy as np

In [2]:
class Test:
    def __init__(self):
        self.x = np.random.randint(0,100000)

In [4]:
test1 = Test()
test2 = Test()
test3 = Test()

In [5]:
test1.x, test2.x, test3.x

(20794, 99790, 3464)

## Hashing

In [11]:
from hashlib import md5, sha224, sha1

In [14]:
s = md5(b"10001101").hexdigest()
print(s)

a5ad4bf861c1c596e63f46293a33d55a


In [18]:
int(s,16)

220222427520596523347357348222660236634

In [20]:
md5().name

'md5'

## Slices

In [22]:
import numpy as np

In [83]:
arr = np.random.randint(0,2,(3,15))
print(arr)

[[0 1 1 0 1 1 1 1 1 1 1 1 0 1 1]
 [0 1 1 1 0 1 1 1 0 1 1 0 1 1 0]
 [1 1 1 0 0 1 0 1 1 0 1 0 0 0 1]]


In [62]:
arr.shape

(3, 15)

In [49]:
def chunk_sizes(start, stop, step):
    l = list()
    curr = 0
    for i in range(start, stop, step):
        curr += min(step, stop-i)
        l.append(curr)
    return np.array(l[:-1])

In [50]:
print(chunk_sizes(0,13,3))

[ 3  6  9 12]


In [46]:
np.split(arr, np.array([3,6,9,12]))

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12])]

In [84]:
spl = np.split(arr, chunk_sizes(0,arr.shape[1],4),axis=1)
spl

[array([[0, 1, 1, 0],
        [0, 1, 1, 1],
        [1, 1, 1, 0]]), array([[1, 1, 1, 1],
        [0, 1, 1, 1],
        [0, 1, 0, 1]]), array([[1, 1, 1, 1],
        [0, 1, 1, 0],
        [1, 0, 1, 0]]), array([[0, 1, 1],
        [1, 1, 0],
        [0, 0, 1]])]

In [73]:
chunk_sizes(0,arr.shape[1],4)

array([ 4,  8, 12])

In [91]:
chunk_size =6
spl = np.split(arr, chunk_sizes(0,arr.shape[1],chunk_size),axis=1)
for i in spl:
    print(i,i.shape,'\n')
    print('\n'.join([''.join(map(str,i[j,:])) for j in range(i.shape[0])]),'\n\n')

[[0 1 1 0 1 1]
 [0 1 1 1 0 1]
 [1 1 1 0 0 1]] (3, 6) 

011011
011101
111001 


[[1 1 1 1 1 1]
 [1 1 0 1 1 0]
 [0 1 1 0 1 0]] (3, 6) 

111111
110110
011010 


[[0 1 1]
 [1 1 0]
 [0 0 1]] (3, 3) 

011
110
001 




## Condition on `tqdm`

In [95]:
from tqdm import tqdm

In [101]:
verbose = True

In [96]:
def verbose_tqdm(gen, **kwargs):
    if verbose:
        return tqdm(gen, **kwargs)
    else:
        return gen

In [102]:
for i in verbose_tqdm(range(10),desc='test'):
    print(i)

test: 100%|██████████| 10/10 [00:00<00:00, 2933.28it/s]

0
1
2
3
4
5
6
7
8
9
